### ISSUE TITLE
Getting following error while running this code 

### ISSUE THREAD

**Issue by rahashwini** [shiba24/learning2rank#12]
RESTART: G:\Implementation of the Project\Learning to Rank Algorithms\Python\ListNet+RankNet\learning2rank-master\rank\ListNet.py 
Traceback (most recent call last):
  File "G:\Implementation of the Project\Learning to Rank Algorithms\Python\ListNet+RankNet\learning2rank-master\rank\ListNet.py", line 18, in <module>
    from learning2rank.utils import NNfuncs
ModuleNotFoundError: No module named 'learning2rank'

**Comment by shiba24** [comment]
Please place this directory (learning2rank) directly under where you want to run the script!

**Comment by pranavpawar3** [comment]
Hi, I have done the same but I am still facing this error,
`ModuleNotFoundError: No module named 'utils'`
Can you please clarify this?
