### ISSUE TITLE
opps, why the python shell in this way after I run ListNet.py?

### ISSUE THREAD

**Issue by davidgao3141** [shiba24/learning2rank#2]
<img width="583" alt="2017-03-01 10 50 21" src="https://cloud.githubusercontent.com/assets/13134696/23465853/74164e70-fed4-11e6-942e-7bb1ef97edd2.png">

**Comment by shiba24** [comment]
What command did you type before the restart? (In the python shell)

**Comment by davidgao3141** [comment]
after installing all these packages 
- python 2.7
- [tqdm](https://github.com/noamraph/tqdm)
- [matplotlib v1.5.1](http://matplotlib.org/)
- [numpy v1.10.1](http://www.numpy.org/)
- [scipy](https://www.scipy.org/)
- [chainer v1.5.1 +](http://chainer.org/)
- [scikit-learn](http://scikit-learn.org/stable/)
I run listnet.py. No other command.

**Comment by shiba24** [comment]
No, this library does not include python script.
Please search "python script module" on google.

**Comment by shiba24** [comment]
And also, do you use virtualenv or conda? Your screen image seems you are using pre-installed python on mac. I don't recommend to use pre-installed python, not only for this package, but also all the python module and scripts you want to run.
I think this error would be not for this package.
