### ISSUE TITLE
Merge from betterenvi repo

### ISSUE THREAD

**Issue by shiba24** [shiba24/learning2rank#3]
Hi @betterenvi
thank you for your modification of this repo!
I looked through your repository (and commits), and think it is a nice change. Could you send a PR to this master branch, if it doesn't bother you?
Thank you for reading!

**Comment by betterenvi** [comment]
@shiba24 , thanks a lot!

I had created a [PR](https://github.com/shiba24/learning2rank/pull/4)

**Comment by shiba24** [comment]
Thank you! I merged it.
