### ISSUE TITLE
how to specify different query?

### ISSUE THREAD

**Issue by waterbeach** [shiba24/learning2rank#5]
I don't know how to set up parameters  for different query

**Comment by shiba24** [comment]
You can see this repo: https://github.com/fullflu/learning-to-rank !

**Comment by yanghaoyun** [comment]
@waterbeach Hello teacher, I have also recently implemented ListNet code, but I do not know what the form of the input data X, y is like? Can a teacher give me an example if it is convenient? ? Thank you teacher
