### ISSUE TITLE
It looks like just a logistic package

### ISSUE THREAD

**Issue by Cauchyzhou** [shiba24/learning2rank#6]
How to deal with many querys?

**Comment by shiba24** [comment]
As I wrote in the readme, ListNet implementation does not include Top-k prob.
You can see this repo: https://github.com/fullflu/learning-to-rank instead.

**Comment by shiba24** [comment]
In some cases, listwise comparison for a given query with JS divergence works better than RankNet, which I found. Also, this repository is already used by another library as a dependency. 
That is why I haven't updated this repo... @Cauchyzhou

**Comment by Cauchyzhou** [comment]
Thank you.
