### ISSUE TITLE
input/output

### ISSUE THREAD

**Issue by nickedes** [shiba24/learning2rank#8]
Hi
Please expalin the input and output formats required for this, is the output of ranknet a probability or a rank?
please clarify

**Comment by shiba24** [comment]
Hi @nickedes , 
as you can see in the README,

> Here, X is numpy array with the shape of (num_samples, num_features) and y is numpy array with the shape of (num_samples, ). y is the score which you would like to rank based on (e.g., Sales of the products, page view, etc).

 Thanks!
